server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://115.159.91.79:3306/lion_devtest?useUnicode=yes&characterEncoding=UTF-8
    username: lion
    password: lion
    driver-class-name: com.mysql.jdbc.Driver

file.storage.root.dir: /home/fileUser/upload/
file.storage.tmp.dir: /home/fileUser/tmp/
